on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Run tests with Bun
    runs-on: ubuntu-latest

    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1.1.1
        with:
          bun-version: latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun Install
        run: bun install
      
      - name: Bun Run Test
        run: bun run test
